version: '3.7'

services: 
  web:
    build: 
      context: .
      args:
        APP_ENVIROMENT: "production"
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/usr/app/
    ports: 
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env.db

volumes:
  postgres_data: